In [14]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import cross_val_score
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_iris
import matplotlib.pyplot as plt
iris = load_iris()

In [ ]:
#Understanding how cross_val_score works
def model_score(model,x_train,x_test,y_train,y_test):
    model.fit(x_train,y_train)
    return model.score(x_test,y_test)
folds = StratifiedKFold(n_splits=3)
array_LogR = []
array_svc = []
array_rfc = []
for train_index, test_index in folds.split(iris.data,iris.target):
  x_train, x_test, y_train, y_test = iris.data[train_index], iris.data[test_index], iris.target[train_index], iris.target[test_index]
  array_LogR.append(model_score(LogisticRegression(),x_train,x_test,y_train,y_test))
  array_svc.append(model_score(SVC(),x_train,x_test,y_train,y_test))
  array_rfc.append(model_score(RandomForestClassifier(),x_train,x_test,y_train,y_test))
print(array_LogR)
print(array_svc)
print(array_rfc)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


[0.98, 0.96, 0.98]
[0.96, 0.98, 0.94]
[0.98, 0.94, 0.98]


In [18]:
#Using cross_val_score
print(cross_val_score(LogisticRegression(),iris.data,iris.target,cv=3, scoring='accuracy'))
print(cross_val_score(SVC(),iris.data,iris.target,cv=3, scoring='accuracy'))
print(cross_val_score(RandomForestClassifier(),iris.data,iris.target,cv=3, scoring='accuracy'))

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


[0.98 0.96 0.98]
[0.96 0.98 0.94]
[0.98 0.94 0.98]
