In [208]:
#Part 1
import pandas as pd
import numpy as np

In [209]:
df = pd.read_csv('4) carprices.csv')
df

Car Model  Mileage  Sell Price($)  Age(yrs)
0                  BMW X5    69000          18000         6
1                  BMW X5    35000          34000         3
2                  BMW X5    57000          26100         5
3                  BMW X5    22500          40000         2
4                  BMW X5    46000          31500         4
5                 Audi A5    59000          29400         5
6                 Audi A5    52000          32000         5
7                 Audi A5    72000          19300         6
8                 Audi A5    91000          12000         8
9   Mercedez Benz C class    67000          22000         6
10  Mercedez Benz C class    83000          20000         7
11  Mercedez Benz C class    79000          21000         7
12  Mercedez Benz C class    59000          33000         5

In [210]:
dummies = pd.get_dummies(df[['Car Model']])
dummies

Car Model_Audi A5  Car Model_BMW X5  Car Model_Mercedez Benz C class
0               False              True                            False
1               False              True                            False
2               False              True                            False
3               False              True                            False
4               False              True                            False
5                True             False                            False
6                True             False                            False
7                True             False                            False
8                True             False                            False
9               False             False                             True
10              False             False                             True
11              False             False                             True
12              False             False                             True

In [211]:
merged = pd.concat([df,dummies],axis = 'columns').drop(['Car Model'], axis = 'columns')

In [212]:
merged = merged.iloc[:,:-1]
merged

Mileage  Sell Price($)  Age(yrs)  Car Model_Audi A5  Car Model_BMW X5
0     69000          18000         6              False              True
1     35000          34000         3              False              True
2     57000          26100         5              False              True
3     22500          40000         2              False              True
4     46000          31500         4              False              True
5     59000          29400         5               True             False
6     52000          32000         5               True             False
7     72000          19300         6               True             False
8     91000          12000         8               True             False
9     67000          22000         6              False             False
10    83000          20000         7              False             False
11    79000          21000         7              False             False
12    59000          33000         5              False             False

In [213]:
from sklearn.linear_model import LinearRegression
model1 = LinearRegression()
X_train1 = np.array(merged.drop(['Sell Price($)'], axis='columns'))
y_train1 = merged['Sell Price($)']
model1.fit(X_train1, y_train1)


LinearRegression()

In [214]:
#Part 2
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
dfle = df
le = LabelEncoder()
ohe = OneHotEncoder()
dfle['Car Model'] = le.fit_transform(dfle['Car Model'])
print(dfle)

    Car Model  Mileage  Sell Price($)  Age(yrs)
0           1    69000          18000         6
1           1    35000          34000         3
2           1    57000          26100         5
3           1    22500          40000         2
4           1    46000          31500         4
5           0    59000          29400         5
6           0    52000          32000         5
7           0    72000          19300         6
8           0    91000          12000         8
9           2    67000          22000         6
10          2    83000          20000         7
11          2    79000          21000         7
12          2    59000          33000         5


In [220]:
x_train2 = dfle[['Mileage','Age(yrs)','Car Model']].values
ct = ColumnTransformer([('Car Model', OneHotEncoder(), [2])], remainder = 'passthrough')
x_train2 = ct.fit_transform(x_train2)
x_train21 = np.hstack((x_train2[:,3:5], x_train2[:,:2]))
x_train2 = x_train21
y_train2 = dfle['Sell Price($)'].values
model2 = LinearRegression()
model2.fit(x_train2, y_train2)
x_train2

array([[6.90e+04, 6.00e+00, 0.00e+00, 1.00e+00],
       [3.50e+04, 3.00e+00, 0.00e+00, 1.00e+00],
       [5.70e+04, 5.00e+00, 0.00e+00, 1.00e+00],
       [2.25e+04, 2.00e+00, 0.00e+00, 1.00e+00],
       [4.60e+04, 4.00e+00, 0.00e+00, 1.00e+00],
       [5.90e+04, 5.00e+00, 1.00e+00, 0.00e+00],
       [5.20e+04, 5.00e+00, 1.00e+00, 0.00e+00],
       [7.20e+04, 6.00e+00, 1.00e+00, 0.00e+00],
       [9.10e+04, 8.00e+00, 1.00e+00, 0.00e+00],
       [6.70e+04, 6.00e+00, 0.00e+00, 0.00e+00],
       [8.30e+04, 7.00e+00, 0.00e+00, 0.00e+00],
       [7.90e+04, 7.00e+00, 0.00e+00, 0.00e+00],
       [5.90e+04, 5.00e+00, 0.00e+00, 0.00e+00]])

In [119]:
#As Our both models are built, we can use and find solutions to our exercise.
#1
model1.predict([[45000,4,0,0]])

array([36991.31721061])

In [221]:
model2.predict([[45000,4,0,0]])

array([36991.31721061])

In [223]:
#2
model1.predict([[86000,7,0,1]])

array([11080.74313219])

In [224]:
model2.predict([[86000,7,0,1]])

array([11080.74313219])

In [225]:
#3
model1.score(X_train1, y_train1)

0.9417050937281082

In [226]:
model2.score(x_train2, y_train2)

0.9417050937281082

In [227]:
import pickle
with open('model_pickle','wb') as f:
    pickle.dump(model1,f)


In [234]:
import joblib as jb
jb.dump(model2, 'model_joblib')

['model_joblib']